baseurl: ""
url: ""
title: "Nila Learns To Write"
author: "Nilanka Weeraman"
language: "en"
description: "Hi there. This is an attempt to learn by writing. Thanks for your interest!"
permalink: /:categories/:title/
markdown: kramdown
plugins: []